import {McpServer} from '@modelcontextprotocol/server';
import {serveStdio} from '@modelcontextprotocol/server/stdio';
import * as z from 'zod/v4';

const BACKEND=process.env.RADAR_BACKEND_URL||'http://localhost:8787';
async function backend<T>(path:string):Promise<T>{const r=await fetch(`${BACKEND}${path}`,{signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Radar backend unavailable');return d;}
const aircraftSchema=z.object({icao24:z.string(),callsign:z.string().nullable(),originCountry:z.string().nullable(),timePosition:z.string().nullable(),lastContact:z.string().nullable(),latitude:z.number().nullable(),longitude:z.number().nullable(),altitudeFt:z.number().nullable(),groundSpeedKts:z.number().nullable(),headingDeg:z.number().nullable(),verticalRateFpm:z.number().nullable(),geoAltitudeFt:z.number().nullable(),onGround:z.boolean().nullable(),squawk:z.string().nullable(),category:z.number().nullable()});
const server=new McpServer({name:'ai-radar-live-flight-tracker',version:'1.0.0',description:'Live aircraft data tools backed by OpenSky Network. Never invent aircraft data.'});
const text=(data:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(data)}],structuredContent:data});
server.registerTool('get_live_aircraft',{description:'Get currently available aircraft from the live OpenSky-backed radar dataset. Use this for current aircraft questions; never invent missing values.',inputSchema:z.object({lamin:z.number().optional(),lomin:z.number().optional(),lamax:z.number().optional(),lomax:z.number().optional(),limit:z.number().int().min(1).max(10000).default(200)}),outputSchema:z.object({source:z.string(),fetchedAt:z.string(),count:z.number(),aircraft:z.array(aircraftSchema)})},async args=>{const p=new URLSearchParams();for(const k of ['lamin','lomin','lamax','lomax','limit'] as const){const v=args[k];if(v!==undefined)p.set(k,String(v));}const d=await backend<any>(`/api/aircraft?${p}`);return text({source:d.source,fetchedAt:d.fetchedAt,count:d.count,aircraft:d.aircraft});});
server.registerTool('search_aircraft',{description:'Search the current live dataset by callsign or ICAO24.',inputSchema:z.object({q:z.string().min(1)}),outputSchema:z.object({source:z.string(),fetchedAt:z.string(),count:z.number(),aircraft:z.array(aircraftSchema)})},async({q})=>{const d=await backend<any>(`/api/search?q=${encodeURIComponent(q)}`);return text(d);});
server.registerTool('get_aircraft_details',{description:'Get one aircraft from the current live dataset by ICAO24.',inputSchema:z.object({icao24:z.string().min(1)}),outputSchema:z.object({source:z.string(),fetchedAt:z.string(),aircraft:aircraftSchema})},async({icao24})=>text(await backend(`/api/aircraft/${encodeURIComponent(icao24)}`)));
server.registerTool('filter_aircraft',{description:'Filter current live aircraft by altitude, speed and heading. Missing numeric fields do not satisfy numeric filters.',inputSchema:z.object({minAltitudeFt:z.number().optional(),maxAltitudeFt:z.number().optional(),minSpeedKts:z.number().optional(),maxSpeedKts:z.number().optional(),minHeadingDeg:z.number().optional(),maxHeadingDeg:z.number().optional()}),outputSchema:z.object({source:z.string(),fetchedAt:z.string(),count:z.number(),aircraft:z.array(aircraftSchema)})},async(args)=>{const d=await backend<any>('/api/aircraft?limit=10000');let a=d.aircraft.filter((x:any)=>(args.minAltitudeFt===undefined||(x.altitudeFt!=null&&x.altitudeFt>=args.minAltitudeFt))&&(args.maxAltitudeFt===undefined||(x.altitudeFt!=null&&x.altitudeFt<=args.maxAltitudeFt))&&(args.minSpeedKts===undefined||(x.groundSpeedKts!=null&&x.groundSpeedKts>=args.minSpeedKts))&&(args.maxSpeedKts===undefined||(x.groundSpeedKts!=null&&x.groundSpeedKts<=args.maxSpeedKts))&&(args.minHeadingDeg===undefined||(x.headingDeg!=null&&x.headingDeg>=args.minHeadingDeg))&&(args.maxHeadingDeg===undefined||(x.headingDeg!=null&&x.headingDeg<=args.maxHeadingDeg)));return text({source:d.source,fetchedAt:d.fetchedAt,count:a.length,aircraft:a});});
server.registerTool('get_aircraft_near_location',{description:'Find the closest currently visible aircraft to a latitude/longitude using the live backend dataset.',inputSchema:z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),radiusKm:z.number().positive().max(2000).default(100),limit:z.number().int().min(1).max(100).default(10)}),outputSchema:z.object({source:z.string(),fetchedAt:z.string(),count:z.number(),aircraft:z.array(aircraftSchema.extend({distanceKm:z.number()}))})},async({latitude,longitude,radiusKm,limit})=>{const d=await backend<any>('/api/aircraft?limit=10000');const a=d.aircraft.filter((x:any)=>x.latitude!=null&&x.longitude!=null).map((x:any)=>({...x,distanceKm:distance(latitude,longitude,x.latitude,x.longitude)})).filter((x:any)=>x.distanceKm<=radiusKm).sort((a:any,b:any)=>a.distanceKm-b.distanceKm).slice(0,limit);return text({source:d.source,fetchedAt:d.fetchedAt,count:a.length,aircraft:a});});
function distance(a:number,b:number,c:number,d:number){const r=6371,rad=(x:number)=>x*Math.PI/180,dl=rad(c-a),dn=rad(d-b),h=Math.sin(dl/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dn/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
void serveStdio(()=>server); console.error('AI Radar MCP server running on stdio');
